### ISSUE TITLE
Need Icon

### ISSUE THREAD

**Issue by RolandPheasant** [RolandPheasant/TailBlazer#15]
I am no designer so would be very happy if someone could design an icon for tail blazer.

Ideally the icon would be provided in .ico format as well as the xaml path.

**Comment by oniony** [comment]
![tail blazer](https://cloud.githubusercontent.com/assets/5895/11296492/4d24b5fc-8f6a-11e5-989f-a1062efec6cb.png)

My only worry is it looks a bit too much like an adult toy.

**Comment by RolandPheasant** [comment]
@oniony this is hilarious

**Comment by ButchersBoy** [comment]
![image](https://cloud.githubusercontent.com/assets/658107/11296551/ad6633fa-8f6a-11e5-8d0f-f6f5e8eff5ac.png)

**Comment by RolandPheasant** [comment]
@ButchersBoy can you convert that into a xaml path

**Comment by oniony** [comment]
I have the SVG. I'll have a look into XAML though I imagine it should be pretty easy conversion of vector to vector.

**Comment by wmaurer** [comment]
@RolandPheasant in #23 you said:
> I quite like this [comet icon](https://icons8.com/web-app/11451/comet). Would be good to see what it looks like in the tray

Here's what it could like like in the tray:

![tailblazer_taskbar_white](https://cloud.githubusercontent.com/assets/2899448/11562343/c79a9032-99cd-11e5-8398-0b87d1af7d19.png)

or

![tailblazer_taskbar_green](https://cloud.githubusercontent.com/assets/2899448/11562350/d13a88ae-99cd-11e5-9fa6-88e09612d9e3.png)

Although I was able to grab the SVG source for this icon, it does cost $5 to buy it, according to the site.

I would be able convert to XAML if you want ...

**Comment by RolandPheasant** [comment]
@wmaurer perhaps I should purchase it and get you to convert it to a xaml path as well as a proper .ico file.  How does that sound?

**Comment by wmaurer** [comment]
Sure, no probs. Buy the SVG, check it into the Images folder and I'll PR in the next days.

**Comment by RolandPheasant** [comment]
Done and waiting for a PR. Thanks

**Comment by wmaurer** [comment]
Which green would you prefer, the darker from the title bar (#388E3C)

![tailblazer_taskbar_green_2](https://cloud.githubusercontent.com/assets/2899448/11602780/42c1d21a-9add-11e5-8462-382372ecd0c6.png)

or the lighter of the FileIcon (#4CAF50)?

![tailblazer_taskbar_green_3](https://cloud.githubusercontent.com/assets/2899448/11602788/5581f9e8-9add-11e5-89ed-eb8e247b61e7.png)

**Comment by RolandPheasant** [comment]
I think it would be better to use the title colour as the icon will also be displayed in the left corner of the title bar.

Shall we try that one first?

**Comment by wmaurer** [comment]
There are numerous ways to set the icon.

One is under Project Properties -> Application. In this case the icon isn't set in the Title Bar.

Another way is to set Icon property in XAML on the window. In this case, the *same* icon (though possibly different size) is shown in the Title Bar and the Task Bar. The problem here is that the icon's background is transparent, and so if the foreground is the same colour as the title bar, all that will be seen is a big green space.

If you want the icon in the Title Bar, I suggest colouring it white. I believe it's possible to have different icons in the Task Bar and Title Bar by way of a simple Win32 call to set the icon on the Window, leaving the Task Bar icon to what's set in the project properties.

**Comment by RolandPheasant** [comment]
The task bar is the priority. Could you do an icon in both colours so I  try and see what's best?

**Comment by wmaurer** [comment]
Sure, I'll do it in the two greens and also in white.

**Comment by RolandPheasant** [comment]
@oniony @ButchersBoy looks like your suggestions have failed :smile:
