### ISSUE TITLE
Change tab naming algorithm

### ISSUE THREAD

**Issue by ForNeVeR** [RolandPheasant/TailBlazer#53]
When I open two files with the same name (for example, `C:\MyProject\x86Debug\Logs\log.txt` and `C:\MyProject\x86DebugServer\Logs\log.txt`), the tab bar looks like this:

![image](https://cloud.githubusercontent.com/assets/92793/11647465/b34be7f2-9d92-11e5-9c0a-b071610ae8de.png)

It is not a very nice; it's hard to distinguish these files. Consider naming the tabs according to the file path fragments that are long enough to distinguish the tabs. For example, here's how Atom renders the tabs for the same two files:

![image](https://cloud.githubusercontent.com/assets/92793/11647565/9d8649b6-9d93-11e5-90b2-cead23a41802.png)

**Comment by RolandPheasant** [comment]
Excellent idea.  I would also like to make the text editable (probably use MaterialDesignToolkit - PopupBox to open an editable control as well as other options)

**Comment by RolandPheasant** [comment]
@ForNeVeR I am a bit busy with some features now, so would you like to write this algorithm?

**Comment by khellang** [comment]
I can PR this if @ForNeVeR isn't up to it :smile:

**Comment by ForNeVeR** [comment]
Guys, currently I am busy a bit on my other projects, so feel free to implement this feature. Thanks for asking though :)

**Comment by RolandPheasant** [comment]
@ForNeVeR no worries at all and keep raising issues as you have identified some important ones. 
@khellang That'll be great.  I see it working something like this:

### Part 1 [name the label]
 - Write an algorithm to label files based on a list of files
 - If there is no duplicate name show the name only eg. 'logger.txt'
 - If there is a duplicate name label fragments eg 'Debug\logger.txt' and also change the other label 

### Part 2 [integrate with the UI]
This will require some thinking because Tail Blazer uses [Dragablz](https://github.com/ButchersBoy/Dragablz) and can docking  do this

![Advanced Docking](https://github.com/RolandPheasant/TailBlazer/blob/master/Images/Docking.gif)

where new tabs become independent windows.  Currently in TB we have a collection for each window so we probably need to re-factor so we have a centralised tab / window collection

### Part 3 [Allow user to rename tabs]

Allowing the user to add an alias a tab would be great. I imagine adding a  PopupBox to each tab header from [MaterialDesignInXamlToolkit](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit). We can treat this one as a separate job.

**Comment by RolandPheasant** [comment]
@khellang I have integrated your code and renamed the class to FileNamer.   The tabs will now automatically rename when opened. Btw I will probably rename it again to FileLabeller!

See [FileHeaderNamingJob.cs](https://github.com/RolandPheasant/TailBlazer/blob/master/Source/TailBlazer/Views/FileHeaderNamingJob.cs).

**Comment by khellang** [comment]
Cool! So it works as expected?

I guess it could make sense to have the same file open multiple times with different filters?

**Comment by khellang** [comment]
In that case, it probably also make sense to include filters in the headers, or allow the user to name the tabs...

**Comment by RolandPheasant** [comment]
Yes I like it so let's see how it rolls.

I would say allow the same file more than once, in which case append (1) or (2) etc and allow the user to change enter something they want.
